import {
  MPC_CONTROL_CANONICALS as CONTROL_LIST,
  MPC_CONSTRAINT_CANONICALS,
  MPC_DISTURBANCE_CANONICALS,
  MPC_EVAL_DATASET_CANONICALS,
  MPC_EVAL_DISTRICT_CANONICALS,
  MPC_EVAL_EXTRA_PLANT_CANONICALS,
  MPC_PLANT_OBSERVATION_CANONICALS,
  MPC_U_MEAS_CANONICALS,
} from "@/lib/sd-anlegg/control/control-signal-registry-360102";

export {
  MPC_CONSTRAINT_CANONICALS,
  MPC_DISTURBANCE_CANONICALS,
  MPC_EVAL_DATASET_CANONICALS,
  MPC_EVAL_DISTRICT_CANONICALS,
  MPC_EVAL_EXTRA_PLANT_CANONICALS,
  MPC_PLANT_OBSERVATION_CANONICALS,
  MPC_U_MEAS_CANONICALS,
};

export const MPC_CONTROL_CANONICALS = CONTROL_LIST;

export type MpcControlCanonical = (typeof MPC_CONTROL_CANONICALS)[number];

export type MpcPlantObservationCanonical =
  (typeof MPC_PLANT_OBSERVATION_CANONICALS)[number];

export const MPC_EVAL_EXTRA_PLANT_SET = new Set<string>(
  MPC_EVAL_EXTRA_PLANT_CANONICALS,
);

export const MPC_U_MEAS_CANONICAL_SET = new Set<string>(MPC_U_MEAS_CANONICALS);

export const MPC_CONTROL_CANONICAL_SET = new Set<string>(MPC_CONTROL_CANONICALS);
