import { InfraspawnSystemDomain } from "@/lib/infraspawn/system-domain";
import type { SchemaTemplate } from "../types";

/** Sekundærkrets fjernvarme / varmeveksler (320.001 / 320.002 / 320.003). Se HEATING-FDV-NAERBYEN.md. */
export const HEATING_DISTRICT_SECONDARY_CIRCUIT: SchemaTemplate = {
  id: "heating.district.secondary_circuit",
  version: 2,
  name: "Fjernvarme krets",
  domains: [InfraspawnSystemDomain.HEATING],
  elementKeyHint: ["320002", "320003"],
  nodes: [
    {
      id: "primary.supply_temp",
      role: "primary.supply_temp",
      lane: "heating",
      componentType: "sensor.temperature",
      label: "Tur inn",
      bind: { kind: "oeSuffix", suffix: "turtemp", allowCrossElement: true },
    },
    {
      id: "primary.return_temp",
      role: "primary.return_temp",
      lane: "heating",
      componentType: "sensor.temperature",
      label: "Retur inn",
      bind: { kind: "oeSuffix", suffix: "returtemp", allowCrossElement: true },
    },
    {
      id: "primary.power",
      role: "primary.power",
      lane: "heating",
      componentType: "generic.signal",
      label: "Effekt",
      bind: { kind: "oeSuffix", suffix: "effekt", allowCrossElement: true },
    },
    {
      id: "primary.energy",
      role: "primary.energy",
      lane: "heating",
      componentType: "generic.signal",
      label: "Energi",
      bind: { kind: "oeSuffix", suffix: "energi", allowCrossElement: true },
    },
    {
      id: "primary.flow",
      role: "primary.flow",
      lane: "heating",
      componentType: "generic.signal",
      label: "Flow",
      bind: { kind: "oeSuffix", suffix: "flow", allowCrossElement: true },
    },
    {
      id: "primary.volume",
      role: "primary.volume",
      lane: "heating",
      componentType: "generic.signal",
      label: "Volum",
      bind: { kind: "oeSuffix", suffix: "volum", allowCrossElement: true },
    },
    {
      id: "compensation.outdoor_temp",
      role: "compensation.outdoor_temp",
      lane: "heating",
      componentType: "sensor.temperature",
      label: "Utetemperatur",
      bind: {
        kind: "equipmentDigits",
        prefix: "RT",
        digits: "901",
        allowCrossElement: true,
      },
    },
    {
      id: "tapwater.supply_temp",
      role: "tapwater.supply_temp",
      lane: "heating",
      componentType: "sensor.temperature",
      label: "Tur tappevann",
      bind: {
        kind: "namedSignal",
        patterns: ["310.001RT402_MV"],
        allowCrossElement: true,
      },
    },
    {
      id: "tapwater.valve",
      role: "tapwater.valve",
      lane: "heating",
      componentType: "hvac.valve",
      label: "Tappevannsventil",
      bind: {
        kind: "equipmentDigits",
        prefix: "SB",
        digits: "501",
        allowCrossElement: true,
      },
    },
    {
      id: "tapwater.pump",
      role: "tapwater.pump",
      lane: "heating",
      componentType: "hvac.pump",
      label: "Tappevannspumpe",
      bind: {
        kind: "equipmentDigits",
        prefix: "JP",
        digits: "501",
        allowCrossElement: true,
      },
    },
    {
      id: "secondary.valve",
      role: "secondary.valve",
      lane: "heating",
      componentType: "hvac.valve",
      label: "Varmeventil",
      bind: { kind: "equipmentDigits", prefix: "SB", digits: "502" },
    },
    {
      id: "secondary.pump_1",
      role: "secondary.pump_1",
      lane: "heating",
      componentType: "hvac.pump",
      label: "Sirkulasjonspumpe 1",
      bind: { kind: "equipmentDigits", prefix: "JP", digits: "401" },
    },
    {
      id: "secondary.pump_2",
      role: "secondary.pump_2",
      lane: "heating",
      componentType: "hvac.pump",
      label: "Sirkulasjonspumpe 2",
      bind: { kind: "equipmentDigits", prefix: "JP", digits: "402" },
    },
    {
      id: "secondary.supply_temp",
      role: "secondary.supply_temp",
      lane: "heating",
      componentType: "sensor.temperature",
      label: "Tur ut",
      bind: { kind: "signalRole", equipmentPrefix: "RT", suffix: "MV" },
    },
    {
      id: "secondary.pressure",
      role: "secondary.pressure",
      lane: "heating",
      componentType: "sensor.pressure",
      label: "Trykk",
      bind: { kind: "equipmentDigits", prefix: "RP", digits: "403" },
    },
    {
      id: "secondary.return_temp",
      role: "secondary.return_temp",
      lane: "heating",
      componentType: "sensor.temperature",
      label: "Retur ut",
      bind: { kind: "equipmentDigits", prefix: "RT", digits: "502" },
    },
    {
      id: "status.setpoint",
      role: "status.setpoint",
      lane: "status",
      componentType: "sensor.temperature",
      label: "Settpunkt",
      bind: {
        kind: "namedSignal",
        patterns: ["RT402_SP", "RT402_SPK", "310.001RT402_SP"],
        allowCrossElement: true,
      },
    },
  ],
  edges: [
    { source: "compensation.outdoor_temp", target: "secondary.valve", edgeType: "pipe" },
    { source: "primary.supply_temp", target: "secondary.valve", edgeType: "pipe" },
    { source: "tapwater.supply_temp", target: "tapwater.valve", edgeType: "pipe" },
    { source: "tapwater.valve", target: "tapwater.pump", edgeType: "pipe" },
    { source: "secondary.valve", target: "secondary.pump_1", edgeType: "pipe" },
    { source: "secondary.pump_1", target: "secondary.pump_2", edgeType: "pipe" },
    { source: "secondary.pump_2", target: "secondary.supply_temp", edgeType: "pipe" },
    { source: "secondary.supply_temp", target: "secondary.pressure", edgeType: "pipe" },
    { source: "secondary.pressure", target: "secondary.return_temp", edgeType: "pipe" },
    { source: "secondary.return_temp", target: "primary.return_temp", edgeType: "pipe" },
  ],
};
